### ISSUE TITLE
clsClipboard error 

### ISSUE THREAD

**Issue by GHallAZ** [renehamburger/blinx#2]
I just downloaded and installed Blinx into Word 2010. I have a document open containing scripture references (e.g. Mark 1:14-15). I have the entire text in the document selected, then left-click once on the icon in Add-Ins to link the scripture with hover text. I get a clsClipboard error (see attached).

Could this be a 32-bit versus 64-bit compatibility issue by chance? If so, is there a solution? I'd really like to give Blinx a try, but it keeps crashing. Help, please!
![blinx issue](https://user-images.githubusercontent.com/32279830/30831540-a2627904-a1fc-11e7-8e94-25b38f5349d9.jpg)

**Comment by olasojiagboola** [comment]
Please is there a solution to this problem as I am having similar problems

**Comment by rob95368** [comment]
This is such a cool add in.  Unfortunately, I'm not able to use it due to the same error.

**Comment by renehamburger** [comment]
I've just updated Blinx again and fixed a few other issues. I have not been able to reproduce the issue you have reported, unfortunately. If one of you wants to give it a try again to see if your issue is still occurring, please let me know.
