### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by wryan6957** [renehamburger/blinx#3]
Using Windows 10 and Office 365. After I copied the blinx.dot into the startup file, when I launch Word and/or try to run the add-in, I get an error "Compile error in hidden module."

**Comment by renehamburger** [comment]
@wryan6957, I just updated the add-in with a few fixes. Would you mind checking again to see if it is working now?

**Comment by wryan6957** [comment]
Yes, I will try to look at it this evening. Thanks!

**Comment by wryan6957** [comment]
Yes!!!

 

I finally had time to figure out how to copy it in, etc. and it is working great on the first couple tries. I did change it to Logos and NIV and it is copying from NIV84, which is my preferred translation in Logos.

 

Thanks so much—this will be a super handy addition for my studies.

 

Warren
